"""Strict request schemas for the CentaurAI Pocket work-secretary domain."""

from .schemas import (
    BusinessTaskCreate,
    CalendarEntryCreate,
    CalendarEntryPatch,
    DocumentCreate,
    DocumentExcerptCreate,
    DocumentGenerate,
    DocumentPatch,
    DocumentReviewCreate,
    MeetingCreate,
    MeetingMinutesCreate,
    MeetingMinutesDecision,
    MeetingParticipantCreate,
    MeetingPatch,
    MemoCreate,
    MemoPatch,
    SourceReference,
    SyncCursorAck,
    TaskChangeCreate,
    TaskChangeDecision,
    TaskPatch,
    TaskStepCreate,
    TaskStepSet,
    TaskTransition,
    VersionCommand,
    WorkspaceMemberCreate,
)

__all__ = [
    "BusinessTaskCreate",
    "CalendarEntryCreate",
    "CalendarEntryPatch",
    "DocumentCreate",
    "DocumentExcerptCreate",
    "DocumentGenerate",
    "DocumentPatch",
    "DocumentReviewCreate",
    "MeetingCreate",
    "MeetingMinutesCreate",
    "MeetingMinutesDecision",
    "MeetingParticipantCreate",
    "MeetingPatch",
    "MemoCreate",
    "MemoPatch",
    "SourceReference",
    "SyncCursorAck",
    "TaskChangeCreate",
    "TaskChangeDecision",
    "TaskPatch",
    "TaskStepCreate",
    "TaskStepSet",
    "TaskTransition",
    "VersionCommand",
    "WorkspaceMemberCreate",
]
