import type { DashboardSummary, DataSource, GovernanceTask } from "@/lib/types";

export const demoDashboard: DashboardSummary = {
  pendingTasks: 12,
  readyItems: 1284,
  totalItems: 1462,
  sourceCount: 4,
  healthySources: 3,
  qualityScore: 92,
  processedToday: 18,
  lastSyncAt: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
};

export const demoTasks: GovernanceTask[] = [
  {
    id: "demo-duplicate-1",
    kind: "deduplicate",
    title: "两份《年度体检报告》可能重复",
    preview: "文件内容相似度 98%，分别来自手机上传与家庭 NAS。",
    sourceName: "健康资料",
    suggestion: "保留清晰度更高的 PDF，另一份作为来源记录。",
    reason: "内容指纹与关键字段高度一致",
    confidence: 0.98,
    createdAt: new Date(Date.now() - 24 * 60 * 1000).toISOString(),
    status: "pending",
    suggestedTitle: "2026 年度体检报告",
    suggestedTags: ["健康", "体检"],
    currentCategory: "健康资料",
    suggestedCategory: "健康资料",
  },
  {
    id: "demo-classify-1",
    kind: "classify",
    title: "将 7 条付款记录归入「家庭财务」",
    preview: "检测到相同商户、银行卡尾号与连续日期。",
    sourceName: "邮箱账单",
    suggestion: "应用分类：财务 / 日常支出 / 订阅",
    reason: "分类模型置信度较高",
    confidence: 0.91,
    createdAt: new Date(Date.now() - 48 * 60 * 1000).toISOString(),
    status: "pending",
    suggestedTitle: "7 条家庭订阅付款记录",
    suggestedTags: ["财务", "日常支出", "订阅"],
    currentCategory: "",
    suggestedCategory: "家庭财务",
  },
  {
    id: "demo-quality-1",
    kind: "quality",
    title: "联系人记录缺少公司字段",
    preview: "“周辰”近期出现在 3 份会议纪要中，但联系人资料不完整。",
    sourceName: "通讯录",
    suggestion: "根据邮件签名补全：星河科技 / 产品部",
    reason: "实体信息存在可补全字段",
    confidence: 0.84,
    createdAt: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
    status: "pending",
    suggestedTitle: "周辰 · 星河科技产品部",
    suggestedTags: ["联系人", "工作"],
    currentCategory: "联系人",
    suggestedCategory: "工作联系人",
  },
  {
    id: "demo-deletion-1",
    kind: "deletion",
    title: "《旧版家庭预算》已从同步文件夹删除",
    preview: "源文件已不存在，当前治理版本仍保留在私人数据库中。",
    sourceName: "家庭 NAS 文件夹",
    suggestion: "归档当前版本，并停止向个人 Agent 提供。",
    reason: "同步扫描确认源文件已删除",
    confidence: 1,
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    status: "pending",
    suggestedTitle: "旧版家庭预算",
    suggestedTags: ["财务", "历史版本"],
    currentCategory: "家庭财务",
    suggestedCategory: "家庭财务",
  },
];

export const demoSources: DataSource[] = [
  {
    id: "demo-folder",
    name: "家庭 NAS 文件夹",
    type: "folder",
    status: "healthy",
    itemCount: 824,
    pendingCount: 2,
    lastSyncAt: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
    errorMessage: null,
  },
  {
    id: "demo-webdav",
    name: "手机 WebDAV",
    type: "webdav",
    status: "syncing",
    itemCount: 376,
    pendingCount: 8,
    lastSyncAt: new Date(Date.now() - 42 * 60 * 1000).toISOString(),
    errorMessage: null,
  },
  {
    id: "demo-mail",
    name: "个人邮箱账单",
    type: "email",
    status: "healthy",
    itemCount: 211,
    pendingCount: 2,
    lastSyncAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    errorMessage: null,
  },
  {
    id: "demo-notes",
    name: "笔记导出目录",
    type: "folder",
    status: "paused",
    itemCount: 51,
    pendingCount: 0,
    lastSyncAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    errorMessage: null,
  },
];
